### ISSUE TITLE
[HOMEWORK] 01/05/2025

### ISSUE THREAD

**Issue by khaddict** [khaddict/homelab#75]
# 1) Fix st2 creation VM workflow

In the workflow, we have a part which remove useless users & setup a defined password for root. This password is retrieved from Vault :

```
{% set root_hash = salt['vault'].read_secret('kv/system').root_hash %}

debian:
  user.absent:
    - purge: True

ubuntu:
  user.absent:
    - purge: True

root:
   user.present:
     - password: {{ root_hash }}
```

The problem is we don't have the right certs to do it :

```
salt 'assets*' state.sls global
assets.homelab.lan:
    Data failed to compile:
----------
    Rendering SLS 'base:global.common.users' failed: Problem running salt function in Jinja template: Failed to read secret! OSError: Could not find a suitable TLS CA certificate bundle, invalid path: /usr/local/share/ca-certificates/ca-homelab.crt; line 1

---
{% set root_hash = salt['vault'].read_secret('kv/system').root_hash %}    <======================

debian:
  user.absent:
    - purge: True

[...]
---
ERROR: Minions returned with non-zero exit code
```

I could simply set the `global.common.ca` part in the independent state (and I'll do this for the moment), but the reality is that if someone access a VM, he can get all the secrets with a salt call. Need to refine this part : [Issue 74](https://github.com/khaddict/homelab/issues/74).

# 2) Fix broken pipe during snapshots

![Image](https://github.com/user-attachments/assets/ab864820-58d2-42d1-828c-cf6e93254251)

# 3) assets.homelab.lan creation

Besoin de fix 1) et 2) avant de pouvoir faire la création de la VM. Ensuite besoin de faire un équivalent de https://github.com/khaddict/assets en GUI (avec base de données)
